import type { Metadata } from "next";
import { Inter, Roboto_Mono, Playfair_Display } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"; // Vercel Analytics
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload background videos so they start instantly */}
        <link
          rel="preload"
          as="video"
          href="/animations/fire.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/animations/ocean.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/animations/nightsky.mp4"
          type="video/mp4"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
